using System.Collections.Generic;

namespace XNote.Utils;

public record AltSymbolItem(string Symbol, string AltCode, string NameRu, string NameEn)
{
    public string DisplayToolTip => $"{LocalizedToolTipName} ({AltCode})";
    private string LocalizedToolTipName => Strings.Current == AppLanguage.Russian ? NameRu : NameEn;
}

public static class AltSymbols
{
    public static readonly IReadOnlyList<AltSymbolItem> Items = new List<AltSymbolItem>
    {
        new("☻", "Alt+2", "Черный смайлик", "Black Smiley"),
        new("♦", "Alt+4", "Бубны", "Diamonds"),
        new("♣", "Alt+5", "Трефы", "Clubs"),
        new("♠", "Alt+6", "Пики", "Spades"),
        new("•", "Alt+7", "Маркер точка", "Bullet"),
        new("◘", "Alt+8", "Квадратный маркер", "Square Bullet"),
        new("○", "Alt+9", "Круг", "Circle"),
        new("◙", "Alt+10", "Инверсный круг", "Inverse Circle"),
        new("♪", "Alt+13", "Нота", "Note"),
        new("♫", "Alt+14", "Две ноты", "Beam Notes"),
        new("☼", "Alt+15", "Солнце", "Sun"),
        new("►", "Alt+16", "Стрелка вправо", "Right Arrowhead"),
        new("◄", "Alt+17", "Стрелка влево", "Left Arrowhead"),
        new("¶", "Alt+20", "Абзац", "Paragraph Sign"),
        new("§", "Alt+21", "Параграф", "Section Sign"),
        new("▬", "Alt+22", "Прямоугольник", "Rectangle"),
        new("↨", "Alt+23", "Стрелка с базой", "Up-Down Base Arrow"),
        new("↑", "Alt+24", "Стрелка вверх", "Up Arrow"),
        new("↓", "Alt+25", "Стрелка вниз", "Down Arrow"),
        new("→", "Alt+26", "Стрелка вправо", "Right Arrow"),
        new("←", "Alt+27", "Стрелка влево", "Left Arrow"),
        new("∟", "Alt+28", "Прямой угол", "Right Angle"),
        new("▲", "Alt+30", "Треугольник вверх", "Triangle Up"),
        new("▼", "Alt+31", "Треугольник вниз", "Triangle Down"),

        new("№", "Alt+0184", "Знак номера", "Number Sign"),
        new("•", "Alt+8226", "Точка маркер", "Bullet Point"),
        new("‣", "Alt+8227", "Треугольный маркер", "Triangle Bullet"),
        new("†", "Alt+0134", "Крестик", "Dagger"),
        new("‡", "Alt+0135", "Двойной крестик", "Double Dagger"),
        new("«", "Alt+0171", "Кавычки елочки левые", "Left Guillemet"),
        new("»", "Alt+0187", "Кавычки елочки правые", "Right Guillemet"),
        new("“", "Alt+0147", "Кавычки лапки левые", "Left Double Quote"),
        new("”", "Alt+0148", "Кавычки лапки правые", "Right Double Quote"),
        new("‘", "Alt+0145", "Одиночная кавычка левая", "Left Single Quote"),
        new("’", "Alt+0146", "Одиночная кавычка правая", "Right Single Quote"),
        new("„", "Alt+0132", "Нижняя кавычка", "Low Double Quote"),
        new("–", "Alt+0150", "Среднее тире", "En Dash"),
        new("—", "Alt+0151", "Длинное тире", "Em Dash"),
        new("…", "Alt+0133", "Многоточие", "Ellipsis"),
        new("¡", "Alt+0161", "Перевернутый восклицательный", "Inverted Exclamation"),
        new("¿", "Alt+0191", "Перевернутый вопросительный", "Inverted Question"),

        new("±", "Alt+0177", "Плюс-минус", "Plus-Minus"),
        new("×", "Alt+0215", "Умножение", "Multiply"),
        new("÷", "Alt+0247", "Деление", "Divide"),
        new("≠", "Alt+8800", "Не равно", "Not Equal"),
        new("≈", "Alt+8776", "Приблизительно равно", "Approximately Equal"),
        new("≡", "Alt+8801", "Тождественно", "Identical"),
        new("≤", "Alt+8804", "Меньше или равно", "Less Than or Equal"),
        new("≥", "Alt+8805", "Больше или равно", "Greater Than or Equal"),
        new("∞", "Alt+8734", "Бесконечность", "Infinity"),
        new("√", "Alt+8730", "Квадратный корень", "Square Root"),
        new("∛", "Alt+8731", "Кубический корень", "Cube Root"),
        new("°", "Alt+0176", "Градус", "Degree"),
        new("′", "Alt+8242", "Минуты штрих", "Prime"),
        new("″", "Alt+8243", "Секунды двойной штрих", "Double Prime"),
        new("µ", "Alt+0181", "Микро", "Micro"),
        new("∑", "Alt+8721", "Сумма", "Summation"),
        new("∏", "Alt+8719", "Произведение", "Product"),
        new("∫", "Alt+8747", "Интеграл", "Integral"),
        new("∬", "Alt+8748", "Двойной интеграл", "Double Integral"),
        new("∂", "Alt+8706", "Частная производная", "Partial Differential"),
        new("∇", "Alt+8711", "Набла", "Nabla"),
        new("∆", "Alt+8710", "Дельта", "Delta"),
        new("∈", "Alt+8712", "Принадлежит", "Element Of"),
        new("∉", "Alt+8713", "Не принадлежит", "Not Element Of"),
        new("⊂", "Alt+8834", "Подмножество", "Subset"),
        new("⊃", "Alt+8835", "Надмножество", "Superset"),
        new("∩", "Alt+8745", "Пересечение", "Intersection"),
        new("∪", "Alt+8746", "Объединение", "Union"),
        new("∅", "Alt+8709", "Пустое множество", "Empty Set"),
        new("∴", "Alt+8756", "Следовательно", "Therefore"),
        new("∵", "Alt+8757", "Так как", "Because"),
        new("∧", "Alt+8743", "Логическое И", "Logical AND"),
        new("∨", "Alt+8744", "Логическое ИЛИ", "Logical OR"),
        new("¬", "Alt+0172", "Отрицание", "Logical NOT"),
        new("‰", "Alt+0137", "Промилле", "Per Mille"),

        new("₽", "Alt+8381", "Символ рубля", "Ruble Sign"),
        new("€", "Alt+0128", "Символ евро", "Euro Sign"),
        new("£", "Alt+0163", "Фунт стерлингов", "Pound Sign"),
        new("¥", "Alt+0165", "Иена Юань", "Yen Sign"),
        new("₴", "Alt+8372", "Гривна", "Hryvnia Sign"),
        new("₸", "Alt+8376", "Тенге", "Tenge Sign"),
        new("₿", "Alt+8383", "Биткоин", "Bitcoin Sign"),
        new("¢", "Alt+0162", "Цент", "Cent Sign"),
        new("¤", "Alt+0164", "Знак валюты", "Currency Sign"),
        new("₧", "Alt+158", "Песета", "Peseta"),
        new("ƒ", "Alt+159", "Флорин", "Guilder"),

        new("½", "Alt+0189", "Одна вторая", "One Half"),
        new("¼", "Alt+0188", "Одна четвертая", "One Quarter"),
        new("¾", "Alt+0190", "Три четвертых", "Three Quarters"),
        new("⅓", "Alt+8531", "Одна треть", "One Third"),
        new("⅔", "Alt+8532", "Две трети", "Two Thirds"),
        new("⅕", "Alt+8533", "Одна пятая", "One Fifth"),
        new("⅖", "Alt+8534", "Две пятые", "Two Fifths"),
        new("⅗", "Alt+8535", "Три пятые", "Three Fifths"),
        new("⅘", "Alt+8536", "Четыре пятых", "Four Fifths"),
        new("⅙", "Alt+8537", "Одна шестая", "One Sixth"),
        new("⅚", "Alt+8538", "Пять шестых", "Five Sixths"),
        new("⅛", "Alt+8539", "Одна восьмая", "One Eighth"),
        new("⅜", "Alt+8540", "Три восьмых", "Three Eighths"),
        new("⅝", "Alt+8541", "Пять восьмых", "Five Eighths"),
        new("⅞", "Alt+8542", "Семь восьмых", "Seven Eighths"),
        new("¹", "Alt+0185", "Степень 1", "Superscript 1"),
        new("²", "Alt+0178", "Степень 2 Квадрат", "Superscript 2"),
        new("³", "Alt+0179", "Степень 3 Куб", "Superscript 3"),
        new("⁴", "Alt+8308", "Степень 4", "Superscript 4"),
        new("⁵", "Alt+8309", "Степень 5", "Superscript 5"),
        new("⁶", "Alt+8310", "Степень 6", "Superscript 6"),
        new("⁷", "Alt+8311", "Степень 7", "Superscript 7"),
        new("⁸", "Alt+8312", "Степень 8", "Superscript 8"),
        new("⁹", "Alt+8313", "Степень 9", "Superscript 9"),
        new("⁰", "Alt+8304", "Степень 0", "Superscript 0"),
        new("ⁿ", "Alt+8319", "Степень n", "Superscript n"),
        new("₀", "Alt+8320", "Нижний индекс 0", "Subscript 0"),
        new("₁", "Alt+8321", "Нижний индекс 1", "Subscript 1"),
        new("₂", "Alt+8322", "Нижний индекс 2", "Subscript 2"),
        new("₃", "Alt+8323", "Нижний индекс 3", "Subscript 3"),
        new("₄", "Alt+8324", "Нижний индекс 4", "Subscript 4"),
        new("₅", "Alt+8325", "Нижний индекс 5", "Subscript 5"),

        new("←", "Alt+8592", "Стрелка влево", "Left Arrow"),
        new("→", "Alt+8594", "Стрелка вправо", "Right Arrow"),
        new("↑", "Alt+8593", "Стрелка вверх", "Up Arrow"),
        new("↓", "Alt+8595", "Стрелка вниз", "Down Arrow"),
        new("⇐", "Alt+8656", "Двойная стрелка влево", "Double Left Arrow"),
        new("⇒", "Alt+8658", "Двойная стрелка вправо", "Double Right Arrow"),
        new("⇑", "Alt+8657", "Двойная стрелка вверх", "Double Up Arrow"),
        new("⇓", "Alt+8659", "Двойная стрелка вниз", "Double Down Arrow"),
        new("⇔", "Alt+8660", "Двойная стрелка влево-вправо", "Double Left-Right"),
        new("➔", "Alt+10140", "Толстая стрелка вправо", "Heavy Right Arrow"),
        new("➜", "Alt+10142", "Узорная стрелка", "Pattern Right Arrow"),
        new("➤", "Alt+10145", "Направляющая стрелка", "Spearhead Arrow"),

        new("α", "Alt+224", "Альфа", "Alpha"),
        new("β", "Alt+225", "Бета", "Beta"),
        new("γ", "Alt+226", "Гамма", "Gamma"),
        new("δ", "Alt+235", "Дельта", "Delta"),
        new("ε", "Alt+238", "Эпсилон", "Epsilon"),
        new("θ", "Alt+233", "Тета", "Theta"),
        new("λ", "Alt+955", "Лямбда", "Lambda"),
        new("µ", "Alt+230", "Мю", "Mu"),
        new("π", "Alt+227", "Пи", "Pi"),
        new("ρ", "Alt+961", "Ро", "Rho"),
        new("σ", "Alt+229", "Сигма", "Sigma"),
        new("τ", "Alt+231", "Тау", "Tau"),
        new("φ", "Alt+237", "Фи", "Phi"),
        new("ω", "Alt+969", "Омега", "Omega"),
        new("Γ", "Alt+915", "Заглавная Гамма", "Capital Gamma"),
        new("Δ", "Alt+916", "Заглавная Дельта", "Capital Delta"),
        new("Θ", "Alt+920", "Заглавная Тета", "Capital Theta"),
        new("Λ", "Alt+923", "Заглавная Лямбда", "Capital Lambda"),
        new("Σ", "Alt+931", "Заглавная Сигма", "Capital Sigma"),
        new("Φ", "Alt+934", "Заглавная Фи", "Capital Phi"),
        new("Ψ", "Alt+936", "Заглавная Пси", "Capital Psi"),
        new("Ω", "Alt+937", "Заглавная Омега", "Capital Omega"),

        new("■", "Alt+254", "Закрашенный квадрат", "Black Square"),
        new("□", "Alt+9633", "Пустой квадрат", "White Square"),
        new("▲", "Alt+30", "Треугольник вверх", "Triangle Up"),
        new("▼", "Alt+31", "Треугольник вниз", "Triangle Down"),
        new("◄", "Alt+17", "Треугольник влево", "Triangle Left"),
        new("►", "Alt+16", "Треугольник вправо", "Triangle Right"),
        new("◆", "Alt+9670", "Ромб", "Black Diamond"),
        new("◇", "Alt+9671", "Пустой ромб", "White Diamond"),
        new("○", "Alt+9", "Круг", "Circle"),
        new("●", "Alt+9679", "Закрашенный круг", "Black Circle"),
        new("◎", "Alt+9673", "Мишень", "Bullseye"),
        new("★", "Alt+9733", "Закрашенная звезда", "Black Star"),
        new("☆", "Alt+9734", "Пустая звезда", "White Star"),
        new("✦", "Alt+10022", "Четырехугольная звезда", "Four Pointed Star"),
        new("✧", "Alt+10023", "Белая звезда", "White Four Pointed Star"),

        new("│", "Alt+179", "Вертикальная линия", "Vertical Bar"),
        new("─", "Alt+196", "Горизонтальная линия", "Horizontal Bar"),
        new("┌", "Alt+218", "Угол верхний левый", "Top-Left Corner"),
        new("┐", "Alt+191", "Угол верхний правый", "Top-Right Corner"),
        new("└", "Alt+192", "Угол нижний левый", "Bottom-Left Corner"),
        new("┘", "Alt+217", "Угол нижний правый", "Bottom-Right Corner"),
        new("├", "Alt+195", "Тройник левый", "T-Left Corner"),
        new("┤", "Alt+180", "Тройник правый", "T-Right Corner"),
        new("┬", "Alt+194", "Тройник верхний", "T-Top Corner"),
        new("┴", "Alt+193", "Тройник нижний", "T-Bottom Corner"),
        new("┼", "Alt+197", "Крестовина", "Cross Corner"),
        new("║", "Alt+186", "Двойная вертикальная", "Double Vertical Bar"),
        new("═", "Alt+205", "Двойная горизонтальная", "Double Horizontal Bar"),
        new("╔", "Alt+201", "Двойной угол верхний левый", "Double Top-Left Corner"),
        new("╗", "Alt+187", "Двойной угол верхний правый", "Double Top-Right Corner"),
        new("╚", "Alt+200", "Двойной угол нижний левый", "Double Bottom-Left Corner"),
        new("╝", "Alt+188", "Двойной угол нижний правый", "Double Bottom-Right Corner"),

        new("✓", "Alt+10003", "Галочка", "Checkmark"),
        new("✕", "Alt+10005", "Крестик отмена", "Multiply Cross"),
        new("✗", "Alt+10007", "Отмена значок", "Ballot Cross"),
        new("✘", "Alt+10008", "Жирный знак отмены", "Heavy Ballot Cross")
    };
}